version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      runtime-production-minor-patch:
        patterns:
          - '*'
        dependency-type: production
        update-types:
          - minor
          - patch
      runtime-development-minor-patch:
        patterns:
          - '*'
        dependency-type: development
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 2
